version: '3'
services:
  lab_db2:
    container_name: db2.laboratorio.com
    privileged: true
    image: ibmcom/db2:11.5.4.0
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=passw0rd
      - DBNAME=DBLAB
    networks:
      - laboratorio
  lab_mq:
    container_name: mq.laboratorio.com
    ports:
      - 9444:9443
    image: ibmcom/mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM_LABORATORIO
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_APP_PASSWORD=passw0rd
    networks:
      - laboratorio
  lab_ldap:
    container_name: ldap.laboratorio.com
    image: lab-ldap
    build: ./lab-ldap-image
    networks:
      - laboratorio
  lab_server1:
    container_name: server1.laboratorio.com
    image: lab-server
    build: ./lab-server-image
    networks:
      - laboratorio
    depends_on:
      - lab_db2
      - lab_mq
      - lab_ldap
  lab_server2:
    container_name: server2.laboratorio.com
    image: lab-server
    networks:
      - laboratorio
    depends_on:
      - lab_db2
      - lab_mq
      - lab_ldap
  lab_web:
    container_name: www.laboratorio.com
    image: lab-web
    build: ./lab-web-image
    ports:
      - 80:80
    networks:
      - laboratorio
    depends_on:
      - lab_server1
      - lab_server2
networks:
  laboratorio: